#!/bin/bash
# refresh-config.sh — Refresh Avalanche local test configuration for ChainSmith
#
# Purpose:
#   Generate and optionally sync the Avalanche local config used by ChainSmith tests.
#   This script only prepares test configuration. It does not run tests.
#
# Usage:
#   chmod +x refresh-config.sh
#   ./refresh-config.sh
#   ./refresh-config.sh --no-sync-main
#
# Optional environment variables:
#   AVALANCHE_CHAIN_NAME   Blockchain name (default: chainsmithavalanche)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
GENERATED_FILE="${PROJECT_ROOT}/tests/config.avalanche.local.generated.json"
MAIN_CONFIG_FILE="${PROJECT_ROOT}/tests/config.json"
SYNC_MAIN="true"

if [ "${1:-}" = "--no-sync-main" ]; then
    SYNC_MAIN="false"
fi

METADATA_JSON="$("${SCRIPT_DIR}/extract-metadata.sh")"

export METADATA_JSON
export GENERATED_FILE
export MAIN_CONFIG_FILE
export SYNC_MAIN

node <<'NODE'
const fs = require('fs');
const path = require('path');

const metadata = JSON.parse(process.env.METADATA_JSON);
const generatedFile = process.env.GENERATED_FILE;
const mainConfigFile = process.env.MAIN_CONFIG_FILE;
const syncMain = process.env.SYNC_MAIN === 'true';

function defaultTestConfig() {
  return {
    performanceExpect: {
      tokenTransfer: {
        runs: 5,
        threshold: 10000,
        percentage: 90,
      },
    },
    faultTolerance: {
      waitTimeForBlock: 10000,
      waitTimeForService: 45000,
      waitTimeLong: 300000,
      timeout: 300000,
    },
  };
}

let existingMainConfig = {};
if (fs.existsSync(mainConfigFile)) {
  existingMainConfig = JSON.parse(fs.readFileSync(mainConfigFile, 'utf8'));
}

const avalancheConfig = {
  description: 'Avalanche local L1 generated by refresh-config.sh',
  avalancheCliChainName: metadata.chainName,
  ecosystem: 'avalanche',
  supportedCosmosModules: [],
  chainType: 'evm',
  executeLayer: 'evm',
  consensusLayer: 'cosmos',
  controlPlane: 'avalanche-platform',
  validatorManagementType: metadata.validatorManagementType,
  chainId: metadata.chainId ?? 9001,
  networkId: metadata.networkId ?? 1337,
  subnetId: metadata.subnetId,
  blockchainId: metadata.blockchainId,
  executeLayerHttpRpcUrl: metadata.representativeL1Node?.executeLayerHttpRpcUrl,
  controlPlaneRpcUrl: metadata.representativeL1Node?.controlPlaneRpcUrl,
  infoApiUrl: metadata.representativeL1Node?.infoApiUrl,
  healthApiUrl: metadata.representativeL1Node?.healthApiUrl,
  transactionConfirmationStrategy: 'receipt-polling',
  transactionConfirmationTimeoutMs: 180000,
  transactionConfirmationPollIntervalMs: 1000,
  executionMethod: 'none',
  nodes: metadata.l1Nodes.map((node, index) => ({
    index: index + 1,
    url: node.uri,
    type: 'validator',
    votingPower: 1,
    active: true,
    executeLayerHttpRpcUrl: node.executeLayerHttpRpcUrl,
    controlPlaneRpcUrl: node.controlPlaneRpcUrl,
    infoApiUrl: node.infoApiUrl,
    healthApiUrl: node.healthApiUrl,
    executeLayerHttpRpcPort: null,
    consensusLayerRpcPort: null,
    consensusLayerHttpRestApiPort: null,
    consensusLayerP2pCommPort: null,
  })),
  founderWallet: {
    name: 'ewoq',
    address: metadata.founderWallet.address,
    privateKey: metadata.founderWallet.privateKey,
    privateKeySource: 'local',
  },
  validatorManagerAddress: metadata.validatorManagerAddress,
  validatorManagerRpcEndpoint: metadata.validatorManagerRpcEndpoint,
  specializedValidatorManagerAddress: metadata.specializedValidatorManagerAddress,
  changeOwnerAddress: metadata.changeOwnerAddress,
  validatorManagerOwner: metadata.validatorManagerOwner,
  proxyContractOwner: metadata.proxyContractOwner,
  feePayerPChainAddress: metadata.changeOwnerAddress,
  validatorLifecycle: {
    feePayerMode: 'stored-key',
    feePayerStoredKey: 'ewoq',
    validatorManagerOwner: metadata.validatorManagerOwner,
    defaultBalance: '0.1',
    defaultWeight: 20,
    removeForce: true,
    minRequiredPChainBalance: '0.11'
  },
  discoveredPrimaryNodes: metadata.primaryNodes,
  discoveredAt: metadata.generatedAt,
};

const generatedConfig = {
  testConfig: existingMainConfig.testConfig || defaultTestConfig(),
  'avalanche-local': avalancheConfig,
};

fs.writeFileSync(generatedFile, JSON.stringify(generatedConfig, null, 2));
console.log(`✅ Wrote generated Avalanche config: ${generatedFile}`);

if (syncMain) {
  const nextMainConfig = {
    ...existingMainConfig,
    testConfig: existingMainConfig.testConfig || defaultTestConfig(),
    'avalanche-local': avalancheConfig,
  };

  if (fs.existsSync(mainConfigFile)) {
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
    const backupPath = `${mainConfigFile}.bak.${timestamp}`;
    fs.copyFileSync(mainConfigFile, backupPath);
    console.log(`📝 Backed up existing tests/config.json to ${backupPath}`);
  }

  fs.writeFileSync(mainConfigFile, JSON.stringify(nextMainConfig, null, 2));
  console.log(`✅ Synced avalanche-local config into ${mainConfigFile}`);
} else {
  console.log('ℹ️ Skipped syncing into tests/config.json (--no-sync-main)');
}

console.log('');
console.log('Next steps:');
console.log('  1. export CHAIN_ENV=avalanche-local');
console.log('  2. pnpm test:avalanche:platform');
console.log('  3. pnpm test:basic');
console.log('  4. pnpm test:rpc:evm');
console.log('  5. pnpm test:performance');
console.log('  5. pnpm test:load:stress');
NODE
